### ISSUE TITLE
C99 Fix

### ISSUE THREAD

**Issue by atomspring** [martin-ueding/xournal#1]
Hello there,
I'm using your fork of Xournal, I had to move the declaration of int i=0 on line 384 in main.c to a new line just above in order to compile without C99.

Seems good otherwise, I'd like to help you implement a button to switch between horizontal and vertical but I don't know much programming, and the UI needs a bit of reworking to make vertical mode look a little less crazy. 

![screenshot - 06062016 - 10 07 28 am](https://cloud.githubusercontent.com/assets/9324477/15824724/8df37a7c-2bce-11e6-906f-cbf5f8d08003.png)
Thanks for this though.

**Comment by martin-ueding** [comment]
It is awesome that you like my fork. I want to have such a button as starting it with a command line option is not very nice. Also the UI workflow is broken as I changed a file generated by glade.

## I will have to see what I can do, I have a rough idea about it.

http://martin-ueding.de/#pk_campaign=Email

Sent from my mobile, please excuse my brevity.

**Comment by martin-ueding** [comment]
I now added a new scope around it, therefore it should compile with C90 now.
